INSERT INTO public.palette_color (color_id, palette_id, color_role)
VALUES (6, 1, 'light shades'),
       (7, 1, 'light accent'),
       (8, 1, 'main brand color'),
       (9, 1, 'dark shades'),
       (10, 1, 'dark accent'),
       (31, 2, null),
       (32, 2, null),
       (33, 2, null),
       (34, 2, null),
       (35, 2, null),
       (36, 2, null),
       (37, 2, null),
       (38, 2, null),
       (39, 2, null),
       (40, 2, null),
       (1, 3, 'light shades'),
       (2, 3, 'light accent'),
       (3, 3, 'main brand color'),
       (4, 3, 'dark shades'),
       (5, 3, 'dark accent'),
       (20, 4, null),
       (21, 4, null),
       (22, 4, null),
       (23, 4, null),
       (25, 4, null),
       (26, 4, null),
       (27, 4, null),
       (28, 4, null),
       (29, 4, null),
       (30, 4, null),
       (11, 5, 'light shades'),
       (12, 5, 'light accent'),
       (13, 5, 'main brand color'),
       (14, 5, 'dark shades'),
       (15, 5, 'dark accent'),
       (16, 6, 'light shades'),
       (17, 6, 'light accent'),
       (18, 6, 'main brand color'),
       (19, 6, 'dark shades'),
       (15, 6, 'dark accent');